version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - //e/dockerized/docker-d8/config_files/mysql:/docker-entrypoint-initdb.d
  drupal:
    image: drupal:8.5-apache
    ports:
      - 8181:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
      - //e/dockerized/docker-d8/modules:/var/www/html/modules/custom
      - //e/dockerized/docker-d8/themes:/var/www/html/themes/
      - //e/dockerized/docker-d8/config_files/settings.php:/var/www/html/sites/default/settings.php
    restart: always
    environment:
      DB_DATABASE: drupal
      DB_USER: root
      DB_HOST: mysql
      DB_PASSWORD: 12345
      DB_PORT: 3307

